service: serverless-parameter-subscriber

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParametersByPath
        - lambda:UpdateFunctionConfiguration
      Resource: "*"

functions:
  parameterSubscriber:
    handler: src/handler.parameterSubscriber

# you can add CloudFormation resource templates here
resources:
  Resources:
    parameterEventRule:
      Type: AWS::Events::Rule
      Properties: 
        Description: Parameter Store Change
        EventPattern: {
          "source": [
            "aws.ssm"
          ],
          "detail-type": [
            "Parameter Store Change"
          ]
        }
        State: ENABLED
        Targets: 
          - Id: parameter-subscriber
            Arn: 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:serverless-parameter-subscriber-${self:provider.stage}-parameterSubscriber'
    
    eventRuleLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties: 
        Action: lambda:InvokeFunction
        FunctionName: 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:serverless-parameter-subscriber-${self:provider.stage}-parameterSubscriber'
        Principal: events.amazonaws.com
        SourceArn:
          Fn::GetAtt:
            - parameterEventRule
            - Arn

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-typescript